- Platform/OpenCore/OpenCoreKernel.c
There are missing line breaks in the strings on lines 318, 486, and 566.
On lines 313, 481 and 561, MinKernel is set to `OcParseDarwinVersion (OC_BLOB_GET (&XXX->MaxKernel))` instead of `OcParseDarwinVersion (OC_BLOB_GET (&XXX->MinKernel))`.
> Fix typos in OpenCoreKernel.c

- Platform/OpenCore/OpenCoreKernel.c
With this, you can set both `MinKernel` and `MaxKernel` to `19`, which will then correctly translate to `190000` and `199999`.
This also fixes parsing of e.g. `19.1`, which would previously be `191000` instead of `190100`.
> Refactor `OcParseDarwinVersion`.

- Docs/Kexts.md
It's a VoodooI2C companion that attaches to ALPS USB touchpads (found in HP Elite X2 G1/G2).
> AlpsT4USB category change

- Docs/AcpiSamples/SSDT-PLUG.dsl
This one should fix issue #814 once and for all. The issue was caused by the SSDT that was adding _DSM Method to a Package (forbidden by ACPI Specification) defined on the DSDT (\_SB.PR00). The new if-condition checks if the object is a Processor. By doing this way, if it finds a Package it doesn't add the _DSM Method.
> Added a check to fix 'Cannot override' bug #814

- Platform/OpenCanopy/OcBootstrap.c
- Platform/OpenCanopy/OpenCanopy.c
- Platform/OpenCanopy/OpenCanopy.h
- Platform/OpenCanopy/Views/BootPicker.c
- Platform/OpenCanopy/Views/BootPicker.h
This change allows the OpenCanopy GUI to auto select the default boot entry after config.plist->MISC->Boot->Timeout expires. 
FYI - I had to move structs declare from BootPicker.c into BootPicker.h so that we can reference those struct from OpenCanopy.c
> Gui timeout

- macbuild.tool
Addresses a few issues flagged by ShellCheck in macbuild.tool.
ShellCheck Refs:
https://github.com/koalaman/shellcheck/wiki/SC2155
https://github.com/koalaman/shellcheck/wiki/SC2164
https://github.com/koalaman/shellcheck/wiki/SC2046
https://github.com/koalaman/shellcheck/wiki/SC2034
> Address Misc Macbuild Tool Issues

- macbuild.tool
Fix for final outstanding warning. Passes ShellCheck.
Tested and builds without error locally ... Should pass TravisCI
> Build: Fix ShellCheck warning in macbuild

- Library/OcAcpiLib/OcAcpiLib.c
Fix bits EFI_ACPI_6_2_SLP_BUTTON and EFI_ACPI_6_2_PWR_BUTTON in FADT to make power button work. These fixes are combined with reset fix (FadtEnableReset).
> Fix bits EFI_ACPI_6_2_SLP_BUTTON and EFI_ACPI_6_2_PWR_BUTTON in FADT

- Docs/AcpiSamples/SSDT-SBUS-MCHC.dsl
Fix compilation with older versions of iASL.
REF: https://www.reddit.com/r/hackintosh/comments/gw4ij7/ssdtsbusmchcdsl_compiles_with_an_error/
> AcpiSamples: Fix SSDT-SBUS-MCHC.dsl compilation

- Docs/Configuration.tex
Add depth option to reduce cloned size (recursion to submodules)
> Docs: Optimise recommended clone cmd

- Docs/Configuration.tex
- Library/OcBootManagementLib/BootEntryInfo.c
This PR adds support for icons for custom entries (acidanthera/bugtracker#1042).
It should try to load an icon for custom entry from the same directory and fallback to trying to load `.VolumeIcon.icns`.
For entry with `Path` = `.../\EFI\path\to\bootloader.efi` it should try to load `.../\EFI\path\to\bootloader.efi.icns`.
I'm not familiar with either UEFI programming nor with OpenCore code, so let me know if I somehow managed to do something wrong in a few lines of code.
> Load icons for custom boot entries

- Docs/AcpiSamples/SSDT-EC-USBX.dsl
can not nest \_SB under \_SB, possible better ways to organize scopes
> correct EC scope in SSDT-EC-USBX.dsl

- Library/OcInputLib/Keycode/AIKShim.c
- Library/OcInputLib/Keycode/AIKShim.h
- Library/OcInputLib/Keycode/AIKSource.c
- Library/OcInputLib/Keycode/AIKSource.h
On some firmware the reseting input protocols upon OpenCore initialization will discard all currently pressed keys on keyboard. This leads to issue where user unable to trigger showing boot picker by just holding OPT key. https://github.com/acidanthera/bugtracker/issues/564 
Alternatively, we can make this behaviour configurable with option `ResetInputProtocols=true/false`, but this seems unnecessary and just removing 'reset' should work everywhere.
> OcInputLib: Do not reset input protocols

- Utilities/ocvalidate/ocvalidate.c
Current ocvalidate will pass the config even if the config file doesn't pass OcConfigurationInit successfully. Add a status check for better utility of ocvalidate.
> Utilities: Add status check for OcConfigurationInit in ocvalidate, return -1 if it fails

- Include/Acidanthera/Library/OcAppleKernelLib.h
- Include/Acidanthera/Library/OcMachoLib.h
- Include/Apple/IndustryStandard/AppleKmodInfo.h
- Include/Apple/IndustryStandard/AppleKxldState.h
- Library/OcAppleKernelLib/KernelCollection.c
- Library/OcAppleKernelLib/KextPatcher.c
- Library/OcAppleKernelLib/KxldState.c
- Library/OcAppleKernelLib/Link.c
- Library/OcAppleKernelLib/PrelinkedContext.c
- Library/OcAppleKernelLib/PrelinkedInternal.h
- Library/OcAppleKernelLib/PrelinkedKext.c
- Library/OcAppleKernelLib/Vtables.c
- Library/OcMachoLib/CxxSymbols.c
- Library/OcMachoLib/Header.c
- Library/OcMachoLib/HeaderX.h
- Library/OcMachoLib/OcMachoLibInternal.h
- Library/OcMachoLib/Relocations.c
- Library/OcMachoLib/Symbols.c
- Library/OcMachoLib/SymbolsX.h
- Platform/OpenCore/OpenCoreKernel.c
- Utilities/TestKextInject/KextInject.c
- Utilities/TestMacho/Macho.c
32-bit prelinked kernel support
> 32-bit prelinking support

- AppleModels/README.md
- Changelog.md
- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
Firmware, as with software and hardware, should not be pluralised.
This PR fixes instances in the docs (strays into fixing some other items as well)
Instances in code comments and similar to be considered later
> Docs: Fix 'Firmware' Pluralisation

- Library/OcSmbiosLib/SmbiosInternal.c
- Library/OcSmbiosLib/SmbiosInternal.h
- Library/OcSmbiosLib/SmbiosPatch.c
Some systems may have multiple memory array tables in SMBIOS. We want to properly include all system memory tables in the case of NUMA systems, but we do not want other tables included, as some systems may have a system ROM table defined. This will cause incorrect information to be displayed in macOS.
> OcSmbiosLib: Properly handle multiple memory array tables

- Library/OcMiscLib/DataPatcher.c
In the rare case that we need to patch the last portion of data, FindPattern will stop 1 byte earlier.
> OcMiscLib: Fix FindPattern on last byte of data

- Utilities/macserial/modelinfo.h
Add new Apple location name from MacBookPro14,1 serial number
> DataBase: Update Apple locations

- Legacy/BootPlatform/BiosVideo/LegacyBiosThunk.c
- Legacy/BootPlatform/CpuDxe/CpuDxe.c
Garbage from memory was poped to CPU flags on return from legacy BIOS int86 calls.
> [OpenDuet] Fix undefined behavior due to uninited memory (issue 1326)

- Library/OcStorageLib/OcStorageLib.c
`EfiDevicePathProtocol` is installed by `OcStorageInitFromFs` but never uninstalled. As it stands, this prevents any application which calls `OcStorageInitFromFs` (even when correctly followed later by calling `OcStorageFree` to clean up) from being able to exit cleanly, as per the comment below.
This PR uninstalls the protocol in what seems to be the obvious correct place.
> OcStorageLib: Uninstall EfiDevicePathProtocol on OcStorageFree

- Utilities/CreateVault/sign.command
Hi,
I notice the attached sign.command that it leaves Keys folder in EFI/OC/
To my understanding, those keys no longer need during the boot process. Its public key was compiled into opencore.efi
I think it would be safer to remove those keys after done with this script
Also, I put the folder Keys under temp folder "/tmp" to prevent create_vault from processing them.
> Clean up keys after done with signing vault

- Include/Acidanthera/Library/OcBootManagementLib.h
- Include/Acidanthera/Library/OcDevicePathLib.h
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcBootManagementLib/BootManagementInternal.h
- Library/OcBootManagementLib/DefaultEntryChoice.c
- Library/OcBootManagementLib/OcBootManagementLib.inf
- Library/OcBootManagementLib/VariableManagement.c
- Library/OcDevicePathLib/OcDevicePathLib.c
- Platform/OpenCore/OpenCoreMisc.c
The firmware may move our boot option away from bootstrap-index. Scan BootOrder for the option by DP suffix. Implicitly fixes issues with boot entry duplication.
> Support reordering Bootstrap by the FW

- Utilities/macrecovery/macrecovery.py
Resolve failure to verify MLB in macrecovery caused by a missing argument to the `get_session()` function
> Provide missing argument to session retrieval

- Include/Acidanthera/Library/OcApfsLib.h
- Library/OcApfsLib/OcApfsConnect.c
- Library/OcApfsLib/OcApfsLib.c
- Platform/OpenCore/OpenCoreUefi.c
OcApfsLib has two functions with very similar naming
- OcApfsConnectDevice
- ApfsConnectDevice
This introduces some potential confusion especially when using as a 3rd party external library. 
This PR tries to remove such with the following changes that also seems to slightly better reflect what they do:
- OcApfsConnectDevice   ->    OcApfsConnectHandle
- ApfsConnectDevice       ->    OcApfsConnectDevice
PS: There are some other functions in `Library/OcApfsLib/OcApfsConnect.c` that are not canonically named that I haven't changed and one of these, `ApfsCheckOpenCoreScanPolicy`, does not appear to be used anywhere.
> Clarify Function Names in OcApfsLib

- Library/OcMainLib/OpenCorePlatform.c
I've double-checked the behaviour before and after this change - when `Automatic` = `false`, OC was previously loading the Smbios SystemUuid value from the DataHub section, as the code appeared to say (and which I am almost sure - especially as there is no comment there - was wrong), and after the change correctly loads it from the Smbios section.
> OpenCorePlatform: Fix reading Smbios.SystemUuid from wrong section

- Docs/Configuration.tex
**"One can do XYZ"**, **"One may try XYZ"** and similar, are technically correct but slightly archaic and sound odd in context. Changed a few lingering examples to be more natural.
> Misc Doc Tweaks

- Include/Acidanthera/Library/OcConfigurationLib.h
- Include/Acidanthera/Library/OcSerializeLib.h
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcMainLib/OpenCoreMisc.c
- Library/OcMainLib/OpenCoreNvram.c
- Library/OcSerializeLib/OcSerializeLib.c
- Library/OcStorageLib/OcStorageLib.c
- Utilities/ocvalidate/ocvalidate.c
This PR adds support for error count cumulation during serialisation check in OcSerializeLib, which closes https://github.com/acidanthera/bugtracker/issues/1467 as well.
> ocvalidate: Support for error count cumulation during OcConfigurationInit call

- Docs/Configuration.tex
Aligns `Data` items with `String` previously done for consistency.
Also makes more succinct by placing verbiage on failsafe next to indicated value as opposed to sentences in notes.
> Further Clarify Failsafe Values

- Include/Acidanthera/Library/OcDeviceTreeLib.h
- Include/Acidanthera/Library/OcMiscLib.h
- Include/Apple/IndustryStandard/AppleMachoImage.h
- Library/DuetBdsLib/BdsConnect.c
- Library/OcAppleImg4Lib/libDER/DER_Decode.c
- Library/OcAppleImg4Lib/libDER/DER_Decode.h
- Library/OcDataHubLib/DataHub.h
- Platform/CrScreenshotDxe/README.md
- Utilities/LogoutHook/nvramdump.c
This fixes some wrong language in the documentation (source code comments and Markdown files), but the purpose of the pull request is really to ask whether you'd accept a pull request for a feature I intend to implement, namely a way to blacklist (via config.plist) certain entries, for example via specifying the partition UUID, so that AddBootEntryFromBootOption will not add them to the boot choices. If it is not an upstreamable change, I wouldn't bother creating this feature, since then the maintenance burden for the change is greater than the gain I'd get (my use case is a multiboot situation with Chromium OS, where I prefer a custom Entries entry for booting its grubx64.efi directly, rather than relying on the bcfg/efibootmgr nvram BootOption) as opposed to just manually deleting the …
> Fix some incorrect spellings of possessive "its" throughout the project

- Utilities/ocvalidate/README.md
- Utilities/ocvalidate/ValidatePlatformInfo.c
- tested!
- have used "special string OEM" instead of just "OEM" in warning, to try to avoid same sort of ambiguity in wording addressed in https://github.com/acidanthera/OpenCorePkg/pull/208
> ocvalidate: allow OEM special string in Generic/SystemUUID

- Utilities/ocvalidate/ocvalidate.c
Slight tweak to OcValidate completion notice.
Main aim is to explicitly let users know when no issues were found.
> Amend OcValidate Completion Feedback

- Library/OcAfterBootCompatLib/OcAfterBootCompatLib.c
Hi,
Assumed here you forgot to store CpuInfo into BootCompat->CpuInfo to be used [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcAfterBootCompatLib/CustomSlide.c#L812).
> OcAfterBootCompatLib: Store BootCompat CpuInfo

- Library/OcBootManagementLib/OcBootManagementLib.c
Minor change, implements preferred behaviours indicated at https://github.com/acidanthera/bugtracker/issues/1536 .
> OCB: make builtin picker start at default OS even when no timeout

- Changelog.md
- Docs/Configuration.tex
- Include/Acidanthera/Library/OcBootManagementLib.h
- Include/Acidanthera/Library/OcStringLib.h
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcBootManagementLib/BootManagementInternal.h
- Library/OcBootManagementLib/DefaultEntryChoice.c
- Library/OcStringLib/OcUnicodeLib.c
Supports custom boot entries added by `Entries` to be the default boot options. Resolves issues with duplicated entries, incorrect boot arguments, and such when it is attempted currently.
> Support custom boot entries as default options

- Include/Apple/Protocol/AppleKeyMapAggregator.h
- Library/OcAppleKeyMapLib/OcAppleKeyMapLib.c
@vit9696 -
Could you confirm that these changes look correct to you too?
- Changes to IN, OUT or OPTIONAL of certain params
- Make signature and method match
Also (not important) minor changes to comment wording: slightly improved at one point; made consistent between method and signature.
If so, fine to commit to master (also helpful, so that I can rebase ongoing efforts for downkeys onto this, instead of including this in downkeys).
> AKMA: Update KEY_MAP_GET_KEY_STROKES method signature

- Library/OcSmbiosLib/SmbiosPatch.c
I don't know if it was intended behaviour, if so, sorry, ignore this pr.
it produces different result for revisions like {0x02, 0x12, 0x0f, 0x00, 0x01, 0x43}
master: 2.1271143
this pr: 2.1270143
> OcSmbiosLib: Fix index in OcSmbiosGetSmcVersion

- Utilities/ocvalidate/ValidateUEFI.c
Understand above or below a threshold but seems clearer to refer to greater or less than the threshold value.
> Clarify Debug Log Message in OcValidate

- Docs/AcpiSamples/Source/SSDT-SBUS-MCHC.dsl
DTGP is not used in _DSM, so this is died code
> Removed dead code

- Application/OpenCore/OpenCore.c
- Library/OcDevicePathLib/OcDevicePathLib.c
Fixes https://github.com/acidanthera/bugtracker/issues/1637
> OcDevicePathLib: Apply separator to multi-node paths

- OpenCorePkg.dsc
When use SignTool sign efi build with CLANGPDB will get the following error.
```
SignTool Error: SignedCode::Sign returned error: 0x800700C1
For more information, please see https://aka.ms/badexeformat
```
edk2 set bouth `ALIGN` and `FILEALIGN` to 32, OpenCore changed `ALIGN` to 4K for page protection but forgot change `FILEALIGN`
According to Microsoft's [PE format](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-windows-specific-fields-image-only) document description. 
```
The value should be a power of 2 between 512 and 64 K, inclusive. The default is 512. If the SectionAlignment is less than the architecture's page size, then FileAlignment must match SectionAlignment.
```
FileAlignment should be set between 512 and 64 K when SectionAlignment is 4K
> Build: Provide 512B file alignment to CLANGPDB to fix SignTool error

- Docs/AcpiSamples/Source/SSDT-PNLF.dsl
the first modification solves blue screen error starting windows from opencore I attach photos
it is caused by Darwin's absence here "OperationRegion(RMP3, PCI_Config, 0, 0x14)"
the change is this : 
If (_OSI ("Darwin")){
inserted at the beginning
with this change the problem is solved.
the second change on ssdt pnlf makes it compatible with cfl generations and above, and if you want you can delete ssdt pnlfcfl.
i tested this ssdt pnlf on cpu i7 1065g7 & i5 10210U & i7 10510u & i7 8565u and it works
> PNLF Fix Error acpi from win boot and add cfl+ support

- .github/workflows/main.yml
Sample Lint Failure Message currently only mentions issues with alphabetical order but failure may be due to format/style issues. 
Message amended to reflect this.
> Account for Format/Style in Sample Lint Failure Message

- Utilities/macrecovery/macrecovery.py
This issue is observed when downloading macOS using macrecovery.py. Text is partially overwritten, and to work around this, spaces can be added to the end of the strings. 
> Download complete!Bs downloaded...
Another approach would be to replace `\r` with `\n`, which should print the text in a new line. However, I am not completely sure how it would affect things in the variety of OSes this tool can be used in.
> Work around partial overwriting of text by adding spaces at the end of the string

- .github/workflows/main.yml
- OpenCorePkg.dsc
- OpenDuetPkg.dsc
- Patches/0006-Fix-for-NOOPT-CLANG38-compilation-with-clang-13.patch
Needs at least clang-12 for successful compilation.
> Build: Made stack-protector guard use global addressing instead of tls.

- Docs/Configuration.tex
- Docs/Flavours.md
- Docs/Libraries.md
- Library/OcCryptoLib/SecureMem.c
- Library/OcHiiDatabaseLib/String.c
- The article 'a' should be used, not 'an', for words starting with consonant sounds (even when the first letter is a vowel).
- Fixed a few informalities, mainly consistent 'OpenCore' in place of random 'OC' appearances, to maintain consistency with the previously established document voice. 
- Other minor fixes
> Fix Article Usage and Misc Informalities

- Library/OcMemoryLib/MemoryAttributes.c
Some firmware implementations may provide an empty Memory Attributes
Table (NumberOfEntries is zero). Avoid calling OcUpdateDescriptors in
this case, as it will lead to division by zero.
This resolves boot failures due to #DE on XPS 15 9560 when Secure Boot
is enabled.
> OcMemoryLib: Avoid rebuilding attributes when MAT is empty

- Docs/Sample.plist
- Docs/SampleCustom.plist
As reported by user Syncretic, author of SurPlus and MonteRand patches, and by others on macrumors, SurPlus patches are not required for Monterey 12.1 (included).
Monterey 12.2 beta does not require them too.
> EDIT (20dec21): It appears that the released Monterey 12.1 does not require either the SurPlus or MonteRand patches. This may change in a later release, but for now, the race condition addressed by SurPlus is no longer an issue in 12.1. (Note that SurPlus is still required for Big Sur 11.3-11.6.2 and Monterey prior to 12.1; MonteRand seems to only be required for 12.1b1 and no other version/beta.)
This PR adds MaxKernel To SurPlus patches.
> Docs: Add MaxKernel for SurPlus patch

- Changelog.md
- Library/OcBootManagementLib/BootEntryInfo.c
Fixes https://github.com/acidanthera/bugtracker/issues/1939
> OcBootManagementLib: Auto-detect `macOS Installer` text label for use when `.disk_label` file cannot be displayed

- Library/OcHdaDevicesLib/OcHdaDevicesLib.c
Add missing CX8200 and CX20724 to OcHdaDevicesLib.c
(https://github.com/acidanthera/bugtracker/issues/1931)
> Add missing CX8200 and CX20724 to OcHdaDevicesLib.c

- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcConfigurationLib.h
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcConfigurationLib/OcConfigurationLib.inf
- Library/OcMainLib/OcMainLib.inf
- Library/OcMainLib/OpenCoreMisc.c
- OpenCorePkg.dsc
- Utilities/ocvalidate/README.md
- Utilities/ocvalidate/ValidateMisc.c
closes https://github.com/acidanthera/bugtracker/issues/1954
TODO:
After merging:
> OcMainLib: Read and set serial PCD values from config

- Docs/Sample.plist
Without Override key ocvalidate is failing.
> Docs: Add Override key for Serial to Sample.plist

- .github/workflows/main.yml
Coverity does not have to be running on macOS, where a bunch of incompatible problems arise. This PR switches the host OS for Coverity to Linux.
> Build: Run Coverity on Linux

- Include/Acidanthera/Library/OcAudioLib.h
- Include/Acidanthera/Library/OcBootManagementLib.h
- Include/Acidanthera/Protocol/OcAudio.h
- Include/Apple/Protocol/AppleVoiceOver.h
- Library/OcAudioLib/OcAudio.c
- Library/OcAudioLib/OcAudioInternal.h
- Library/OcAudioLib/OcAudioVoiceOver.c
- Library/OcBootManagementLib/BootAudio.c
- Library/OcBootManagementLib/BuiltinPicker.c
- Library/OcBootManagementLib/OcBootManagementLib.c
- Library/OcMainLib/OpenCoreUefiAudio.c
- Platform/OpenCanopy/OcBootstrap.c
- Platform/OpenCanopy/OpenCanopy.c
- Platform/OpenCanopy/Views/BootPicker.c
- Platform/OpenCanopy/Views/Common.c
- Platform/OpenCanopy/Views/Password.c
I've had a chance to do a bit of work on https://github.com/acidanthera/bugtracker/issues/1777.
This is the first part, upgrading OC_AUDIO_PROTOCOL so that sound files are specified by string rather than int, to make it possible to implement system actions with support for audio assist in BootEntryProtocol next.
> OcAudio: Convert from int ids to string ids

- Changelog.md
Removed ocvalidate validation note as duplicate. I am not sure if source code note is ok or not.
Thanks @PMheart for your comments.
> Remove validation note as already existing in ocvalidate Readme

- Legacy/BootPlatform/EfiLdr/EfiLoader.c
- Library/OcBootManagementLib/VariableManagement.c
- Library/OcHiiDatabaseLib/ConfigKeywordHandler.c
- Library/OcHiiDatabaseLib/ConfigRouting.c
- Library/OcHiiDatabaseLib/Font.c
- Library/OcHiiDatabaseLib/HiiDatabase.h
- Library/OcMainLib/OpenCoreMisc.c
- Utilities/ocvalidate/ValidateMisc.c
@mhaeuser - Do you quickly want to check this PR for https://github.com/acidanthera/bugtracker/issues/2009 ?
I think it's pretty uncontroversial - compiles and runs, anyway! ;)
FYI I searched for `StrSize`, `StrLen`, `AsciiStrSize` or `AsciiStrLen` applied to any of `"...`, `L"...` and anything starting with more then one upper case char (to try to get #defines). I auto-replaced for the `"` and `L"` ones, manually checked for correct matches for the (few) #define ones. Let me know if there's anything else I would have missed.
> Various: Static string optimisations

- Include/Acidanthera/Library/OcDevicePathLib.h
- Include/Apple/IndustryStandard/AppleEfiBootRtInfo.h
- Library/OcAfterBootCompatLib/BootCompatInternal.h
- Library/OcAfterBootCompatLib/CustomSlide.c
- Library/OcAfterBootCompatLib/KernelSupport.c
- Library/OcAfterBootCompatLib/RelocationBlock.c
- Library/OcAfterBootCompatLib/ServiceOverrides.c
- Library/OcDevicePathLib/OcDevicePathLib.c
macOS 13 Developer Beta 1 introduced a new driver, bootrt.efi, which
now carries the kernel call gate. It communicates with efiboot via an
info buffer passed via LoadOptions. Patch it on load with our hook to
run our kernel entry code.
> Support AvoidRuntimeDefrag for macOS 13 DP1

- Docs/Configuration.tex
The passage reads like 0 turns off trim timeout, but it actually turns off trim based on the context. dortania/bugtracker#192
> ApfsTrimTimeout: replace ambiguous "it"

- Utilities/CreateVault/create_vault.sh
- Utilities/CreateVault/sign.command
Some notes:
- the plist output functions produce the exact same plist outputs as PlistBuddy as far as I've been able to tell.
- I'm piping the find output through sort with LC_COLLATE=POSIX to have it behave the same on linux as it does on macos. (doesn't matter functionally since OpenCore doesn't care about the order, but it's just nice to have the exact same vault.plists produced on all platforms)
- have to use awk instead of cut in sign.command since binutils (on linux) "strings -t d" outputs numbers that are padded with spaces on the left, whereas that isn't the case on macos apparently.
- the memtest86 things aren't really related, but seem like no brainers to include anyway
- it is still the user's responsibility to compile RsaTool (from Utilities/RsaTool) for their platform and …
> CreateVault linux portability

- Include/Acidanthera/Library/OcAppleKernelLib.h
- Library/OcAppleKernelLib/CommonPatches.c
Patcher can be NULL when the kext is not found; this should not lead to assertion.
> OcAppleKernelLib: Make quirk Patcher parameter optional

- Include/Acidanthera/Library/OcAppleKernelLib.h
- Include/Acidanthera/Library/OcMachoLib.h
- Library/OcAppleKernelLib/CommonPatches.c
- Library/OcAppleKernelLib/CpuidPatches.c
- Library/OcAppleKernelLib/KernelCollection.c
- Library/OcAppleKernelLib/KextPatcher.c
- Library/OcAppleKernelLib/Link.c
- Library/OcAppleKernelLib/MkextContext.c
- Library/OcAppleKernelLib/PrelinkedContext.c
- Library/OcAppleKernelLib/PrelinkedKext.c
- Library/OcAppleKernelLib/Vtables.c
- Library/OcMachoLib/Header.c
- Library/OcMachoLib/HeaderX.h
- Library/OcMachoLib/Relocations.c
- Library/OcMachoLib/SymbolsX.h
- Utilities/TestMacho/Macho.c
As of macOS 13 Developer Beta 3, the Kernel Collection's inner kernel
references a segment that precedes itself. The current model is that
a Kernel Collection is a container format and the included files are
(mostly) separate. Hence, this was treated as an out-of-bounds issue.
Kernel Collections apparently are rather an unconventional composite
format, where the sub-files are still part of the whole. Redesign
OcMachoLib to treat the Kernel Collection as the reference file.
Patches still use only the inner file, while parsing considers the
whole file.
> Support macOS 13 DP3 Kernel Collection

- .gitignore
- Include/Acidanthera/Library/OcAppleKernelLib.h
- Library/OcAppleKernelLib/CachelessContext.c
- Library/OcAppleKernelLib/MkextContext.c
- Library/OcAppleKernelLib/PrelinkedContext.c
- Library/OcMainLib/OpenCoreKernel.c
- Utilities/TestKextInject/KextInject.c
closes https://github.com/acidanthera/bugtracker/issues/2082
This PR fixes the cases of use after free in OcAppleKernelLib.
CC and thanks @mhaeuser
> OcAppleKernelLib: Fix user after free

- Docs/Configuration.tex
- Library/OcAfterBootCompatLib/ServiceOverrides.c
- Library/OcMainLib/OpenCoreAcpi.c
- Library/OcMainLib/OpenCoreKernel.c
- Library/OcMainLib/OpenCoreKernelPatch.c
The current behaviors of how our modification to `Booter` and `Kernel` are undocumented. In addition, we should ensure that:
- Deletion is always performed first, as it makes no sense to patch something that will be removed
- Integrated quirks are always applied preceding user patches (to prevent users from messing up the whole patch structure)
- Injection is performed last
TODO:
> OcMainLib: Patch order change

- Include/Acidanthera/Library/OcDeviceTreeLib.h
- Include/Apple/IndustryStandard/AppleBootArgs.h
- Library/OcAfterBootCompatLib/BootCompatInternal.h
- Library/OcAfterBootCompatLib/KernelSupport.c
- Library/OcAfterBootCompatLib/RelocationBlock.c
- Library/OcAfterBootCompatLib/ServiceOverrides.c
Implements macOS 10.4 and 10.5 support for relocation blocks while using the AllowRelocationBlock booter quirk.
This is required due to XNU in 10.4 and 10.5 having a _TEXT base address of 0x111000, different from 0x200000 in 10.6 and later. SetVirtualAddressMap is also always invoked by EfiBoot even when using a relocation block.
> OCAB: Implement macOS 10.4/10.5 relocation block support

- User/Makefile
We renamed `merge` to `cmin` in Sydr 1.8.0. Moreover, libFuzzer `-jobs=1000 -workers=$(FUZZ_JOBS)` asks fuzzer to find 1000 crashes/ooms/timeouts in `FUZZ_JOBS` fuzzing processes.
> Update Sydr config

- Docs/Configuration.tex
`Plist Dict` config items should not have failsafe values defined.
NB: Docs say contributors should not build the PDFs ... so they will need building by a team member if merged.
> Remove Redundant/Confusing Failsafe Definitions

- Utilities/ocpasswordgen/ocpasswordgen.c
This changes should hides characters on password input. In this case I use getch from conio.h library on Windows and also implemented getch for unix using unistd and termios standard libraries.
> ocpasswordgen: Hide password characters on input

- Library/OcAppleKernelLib/CommonPatches.c
- Library/OcAppleKernelLib/CpuidPatches.c
By adding status indicator (`[OK]` or `[FAIL]`), it is easier to filter messages in TestProcessKernel.
> OcAppleKernelLib: Add patching status indicator

- Changelog.md
- Library/OcCpuLib/FrequencyDetect.c
I think this is correct and with no unwanted side effects.
Note previously, by definition, the call to InternalCalculateARTFrequencyIntel inside OcGetTSCFrequency was capable of returning a zero result (otherwise it would never drop through to the other options), however it never cached a zero result and always recalculated it (and therefore always logged while doing so).
The updated code follows exactly the pattern already used in InternalCalculateTSCFromApplePlatformInfo.
> OcCpuLib: Cache InternalCalculateARTFrequencyIntel failure to avoid log loop

- Utilities/macrecovery/recovery_urls.txt
- Added Monterey recovery command, set to Mac-E43C1C25D4880AD6 (MacBookPro12,1)
- Updated "Latest Version" command to Mac-B4831CEBD52A0C4C (MacBookPro14,1)
Not sure if you want the "Diagnostics" and "Default version" changed to Mac-B4831CEBD52A0C4C too.
> macrecovery: Update for Ventura

- Library/OcAppleKernelLib/CpuidPatches.c
Initial TSC frequency calculation for AMD processors differs somewhat from the frequency calculation for Intel processors. Without special treatment for AMD processors, macOS suffers from TSC de-sync particularly if the AMD processor has on-board GPU. This in turn leads to significant amounts of audio stutter across the entire audio subsystem. This PR has been tested on both AMD and Intel processors to ensure proper operation for both platforms.
> TSC/FSB Fix for AMD CPUs

- Changelog.md
- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcConfigurationLib.h
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcMainLib/OpenCoreMisc.c
- Utilities/ocvalidate/ValidateMisc.c
Allows for seamless wake from hibernation, and avoids situation where someone may accidentally change the boot option when waking. Tests were conducted on a genuine MacBookPro11,3
Notes:
* Changes ShowPicker logic to be a string, takes following inputs:
* `Always` - Show Picker regardless (previously `ShowPicker=True`).
* `Never` - Never Show Picker (previously `ShowPicker=False`).
* `SkipOnHibernateWake` - Hide Picker if machine is waking from macOS Hibernation.
* Picker will still be shown if invoked via PollAppleHotKeys' Option/Esc keys.
* Explicit setting to avoid accidental boot loops from botched Hibernation Configurations (Primarily PCs) where user may not realize or doesn't have PollAppleHotKeys enabled.
* Currently only detects macOS Hibernation, Linux and Windows Hibernation …
> Hide Picker when waking from macOS Hibernation

- Utilities/macrecovery/macrecovery.py
I know this sounds stupid but since the only possible way to use the Internet Recovery Install method is `macrecovery.py`, I thought it would be great that the script creates the folder `com.apple.recovery.boot` where the downloaded image and chunklist goes.
Proof of work:
> [macrecovery] Create `com.apple.recovery.boot`

- User/Include/UserMemory.h
- User/Library/UserBaseMemoryLib.c
- User/README.md
- Utilities/TestDiskImage/DiskImage.c
This changes should help us more accurately control pool allocations during fuzzing, as for example the handling of OOM-states. We provides options to limit by size total allocated memory and to limit maximum size of single allocation operation.
It is still open for discussion the size of these limits and the interface for changing them ("Set" routines in User Memory header)
> User: Add pool allocation size configurable limits for UserBaseMemoryLib

- Platform/OpenVariableRuntimeDxe/VariableDxe.c
UEFI 2.x spoofing, including `ForgeUEFI` in OpenCore, tend to only spoof one element of the system table. Hence, a test on single elements will pass, and UEFI 2.x assumed to be present, if the test happens to be on the spoofed element. 
This is more so the case where OpenCore may be loaded by other tools that may have spoofed the element being tested here. While loading via other tools may not be sanctioned, it is regardless best to always ensure that UEFI 2.x cannot be wrongly assumed under any circumstance.
The proposed change does the following:
- Ensures all system table elements are UEFI 2.x
- Ensures QueryVariableInfo is actually available
This ensures QueryVariableInfo is not set under any type of spoofed UEFI 2.x environment but should there be actual UEFI 2.x emulation at some …
> "Spoof Proof" Setting UEFI 2.x Member

- Changelog.md
- Docs/Configuration.tex
Some minor tweaks for clarity
Mainly:
- Changelog.md: Reworded to better convey intent given that there are no MP51 specific GPUs as was implied
- Configuration.tex: Reworded for clarity on VM and better outline support scope on Apple Hardware
- Previously _suggested_ support only goes as far as MP51 but MP31 is effectively the  boundary
> Minor Tweaks to Docs

- .github/workflows/analyze.yml
- .github/workflows/build.yml
- .github/workflows/uncrustify.yml
- Changelog.md
- Library/OcCpuLib/FrequencyDetect.c
- OpenCorePkg.dsc
- OpenDuetPkg.dsc
This change correct OpenCorePkg build for updated underlying EDK II package with edk2-stable202211tag
> Update to EDKII 202211 stable tag

- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- Dockerfiles/oc-dev-docs/Dockerfile
- Dockerfiles/oc-dev-edk2/Dockerfile
- compose-dev.yaml
- docker-compose.yaml
Docker allows to set up a portable development environment in a container. This can be useful to test Linux toolchains on macOS. Introduce such environments for EDK II and documentation development.
The current implementation supports both Dev Environments by Docker Desktop and Dev Containers by Visual Studio Code. To reduce the maintenance burden, use these environments for the Linux-based GitHub Actions as well. Non-x86 hosts, including Apple Silicon, are supported via GCC cross-compilation.
> Introduce Docker setup for Dev Containers and CI

- User/Library/UserMisc.c
- User/Library/UserPcd.c
The CpuBreakPoint in UserMisc normally shouldn't enter dead-loop condition, instead it should break the program using abort signal. Also sets DEBUG_PROPERTY_ASSERT_BREAKPOINT_ENABLED bit by default in PcdDebugPropertyMask. As a background was a problem with fuzzing when program process falls into dead-loop condition instead of just to exit with crash
> User: Corrects ASSERT behavior in UserPcd

- Changelog.md
- build_oc.tool
This might be useful - as discussed EfiRom is useful for EnableGop vBiosInsert.sh script - it's not particularly easy to find pre-built [EDK-II BaseTools](https://edk2-docs.gitbook.io/edk-ii-basetools-user-guides/tianocompress) (perhaps especially for macOS), and it is easy for us to provide them.
Adds about 1Mb to the release zip size.
> Build: Provide EDK-II BaseTools in releases

- Changelog.md
- Docs/Configuration.tex
- Include/Acidanthera/Library/OcConsoleLib.h
- Library/OcConsoleLib/GopInfoDump.c
- Library/OcConsoleLib/GopUtils.c
- Library/OcConsoleLib/OcConsoleLib.inf
Should fix @khronokernel's issue; also fixes the issue observed on [PeterHolbrook](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/post-32075548)'s graphics card (thx for assistance).
Since it adds a couple of new GOP utilities, I thought I would PR rather then push it directly. The new `GopUtils.c:OcGopModeBytesPerPixel` method here overlaps in functionality with the existing `OcBlitLib.c:BlitLibConfigurePixelFormat` but I thought it was best not to try to merge them, since getting a reliable bytes per pixel value is generally useful, wheres the existing BLIT configure method sets up some other things rather specific to its application (shl and shr values).
> OcConsoleLib: Additional info in GOP dump; additional guards on GopBurstMode

- Library/OcAppleKernelLib/CommonPatches.c
As it says in the comment that the check can be removed if an older version can be injected correctly.
If you have an Ivy Bridge CPU or older that uses the AppleIntelCPUPowermanagent and AppleIntelCPUPowerManagementClient kexts you can inject these ones [from the OCLP project](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main/payloads/Kexts/Misc) and they will work in Ventura but only if you have the CFG lock previously disabled or else there will be a kernel panic 
The PR removes the Ventura check to allow the patch to work in the injected kexts so its no longer necessary to unlock the CFG lock. Already tested with a build and the patch is working correctly
> OcAppleKernelLib: Remove Ventura check for AppleCpuPmCfgLock

- Changelog.md
- Library/OcAppleKernelLib/CommonPatches.c
This closes https://github.com/acidanthera/bugtracker/issues/2256.
Thanks [@fusion71au](https://www.insanelymac.com/forum/profile/846696-fusion71au/) for discovering this.
Ref: https://www.insanelymac.com/forum/topic/350754-opencore-general-discussion/page/337/#comment-2803365
> OcAppleKernelLib: Fix ExternalDiskIcons quirk on macOS 13.3+

- Changelog.md
- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcConfigurationLib.h
- Include/Acidanthera/Library/OcConsoleLib.h
- Library/OcBootManagementLib/BuiltinPicker.c
- Library/OcBootManagementLib/OcBootManagementLib.c
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcConsoleLib/ConsoleControl.c
- Library/OcConsoleLib/OcConsoleLib.c
- Library/OcConsoleLib/OcConsoleLibInternal.h
- Library/OcConsoleLib/TextOutputBuiltin.c
- Library/OcConsoleLib/TextOutputSystem.c
- Library/OcMainLib/OpenCoreUefiInOut.c
- Platform/OpenCanopy/OcBootstrap.c
- Staging/EnableGop/EnableGop.c
- Staging/EnableGop/EnableGop.inf
- Staging/EnableGop/EnableGopDirect.inf
- Staging/EnableGop/README.md
- Utilities/ocvalidate/ValidateUefi.c
Apologies for earlier fat finger.
Here it is as a PR.
Commit to go to back to how everything was is now on master, as agreed. But note this causes I believe one different reversion outside of EnableGop (namely initial verbose boot text writes over graphics picker; see subsequent comment for more details), and multiple reversions inside EnableGop (which is temporarily disabled from bundling in OC as agreed).
Then, still in this PR itself:
- First commit is meant to be non-controversial changes to BuiltinRenderer
- Second commit implements InitialMode option
- Third and fourth commits attempt to address all desiderata (see below)
- Fifth commit (seemed like a good idea) supports ConsoleMode text resolution option in Builtin renderer
- Sixth just syncs changelog
My understanding (very …
> Fix console

- Docs/Configuration.tex
- Library/OcMainLib/OpenCoreAcpi.c
Closes https://github.com/acidanthera/bugtracker/issues/2275
This fixes regression introduced by https://github.com/acidanthera/OpenCorePkg/commit/f604848c61d7082860fceb23ac54d5e03e620478.
> OcMainLib/OpenCoreAcpi: Fix orders for `RebaseRegions` and `SyncTableIds`

- .github/workflows/build.yml
This closes https://github.com/acidanthera/bugtracker/issues/1962, as the issue has been fixed upstream.
> Build: Use latest Windows image

- Docs/Configuration.tex
- Staging/AudioDxe/AudioDxe.c
- Staging/AudioDxe/AudioDxe.h
- Staging/AudioDxe/HdaCodec/HdaCodec.c
Provides boot time reduction (especially printing verbose) when used in conjunction with ```--force-device``` and we don't use the other codecs anyways.
Possible to also add an option to use bitmask for outputs but I don't think that's worth the insignificant boot time gain.
On my system most of the time is consumed checking output amps, even though only one is used afaik (output bitmask 2)
```
00:631 00:006 OC: Driver AudioDxe.efi at 1 needs connection.
00:637 00:005 OC: Connecting drivers...
00:649 00:011 HDA: Connecting controller - PciRoot(0x0)/Pci(0x1B,0x0)
00:655 00:006 HDA: Controller disable no snoop
00:660 00:004 HDA: Controller version 1.0
00:665 00:004 HDA: Capabilities:
00:669 00:003 HDA:  | 64-bit: Yes  Serial Data Out Signals: 0
00:675 00:006 HDA:  | Bidir streams: 0  Input …
```
> AudioDxe: Add --force-codec

- Docs/AcpiSamples/Source/SSDT-SBUS-MCHC.dsl
According to https://www.insanelymac.com/forum/topic/233292-patching-sbus-in-dsdt/?do=findComment&comment=1561152, which is the earliest discussion of DVL0 device in SSDT-SBUS I can found,
> This "diagsvault" is the diagnostic vault where messages are stored. It's located at address 87 (0x57) on the SMBus controller. More about the specific SMBus controllers in your hack, can be found in the Intel datasheet (use Google).
By looking into several motherboard datasheets and SMBus specifications, I see Intel makes changes starting from 7 series.
Looking into [Intel® 7 Series / C216 Chipset Family Platform Controller Hub (PCH)](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/7-series-chipset-pch-datasheet.pdf#page807) pg. 807,
> SPD Write Disable — R/WO.
0 = SPD write …
> Docs: Comment DVL0 device in SSDT-SBUS-MCHC

- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcConfigurationLib.h
- Include/Acidanthera/Library/OcPciIoLib.h
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcMainLib/OcMainLib.inf
- Library/OcMainLib/OpenCoreUefi.c
- Library/OcPciIoLib/OcPciIoLib.c
- Library/OcPciIoLib/OcPciIoLib.inf
- Library/OcPciIoLib/OcPciIoU.c
- Library/OcPciIoLib/OcPciIoU.h
- OpenCorePkg.dsc
This UEFI has several bugs relating to 4G Decoding which need to be fixed
* PciRootBridgeIo Mem can't access above 4GB MMIO (Done)
* CpuIo can't access above 4GB MMIO (Done)
* PciIo can't access extended configuration. ```ResizeUsePciRbIo``` works around this for resizable BAR
Boot audio now plays on my system with this patch. Loading time is kinda slow configuring the amp but seems similar to original PciIo.
> 4G Decoding CpuIo/PciRootBridgeIo/PciIo fix for Aptio 4 / Ivy Bridge

- Changelog.md
- Library/OcAppleKernelLib/CommonPatches.c
Closes https://github.com/acidanthera/bugtracker/issues/2297
> OcAppleKernelLib: Integrate USB restriction patches

- Changelog.md
- Docs/Configuration.tex
- Include/Acidanthera/Library/OcAppleBootPolicyLib.h
- Include/Acidanthera/Library/OcBootManagementLib.h
- Include/Acidanthera/Library/OcDevicePathLib.h
- Library/OcAppleBootPolicyLib/OcAppleBootPolicyLib.c
- Library/OcBootManagementLib/BootEntryInfo.c
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcBootManagementLib/BootManagementInternal.h
- Library/OcDevicePathLib/OcDevicePathLib.c
Optionally allow .contentVisibility in the boot fs root locations that are currently searched for .VolumeIcon.icns, since file next to boot.efi is deleted on macOS update.
> OcBootManagementLib: Unify boot meta file loading code;

- Legacy/BootPlatform/BlockIoDxe/BiosBlkIo.c
- Legacy/BootPlatform/BlockIoDxe/BiosBlkIo.h
- Legacy/BootPlatform/BlockIoDxe/BiosInt13.c
- Legacy/BootPlatform/BlockIoDxe/BlockIoDxe.inf
- Legacy/BootPlatform/BlockIoDxe/BlockIoDxe.uni
- Legacy/BootPlatform/BlockIoDxe/BlockIoDxeExtra.uni
- Legacy/BootPlatform/BlockIoDxe/ComponentName.c
- Legacy/BootPlatform/BlockIoDxe/Edd.h
- Legacy/BootPlatform/BlockIoDxe/LegacyBiosThunk.c
- Legacy/BootSector/Makefile
- OpenDuetPkg.dsc
- OpenDuetPkg.fdf
- OpenDuetPkgDefines.fdf.inc
- Utilities/LegacyBoot/BootInstallBase.sh
- Utilities/LegacyBoot/BootInstall_IA32_BlockIO.tool
- Utilities/LegacyBoot/BootInstall_X64.tool
- Utilities/LegacyBoot/BootInstall_X64_BlockIO.tool
- build_duet.tool
- build_oc.tool
Adds support for BIOS INT13h booting via BlockIoDxe in OpenDuet for systems that are poorly supported and unsupported by the USB and ATA/AHCI drivers.
Closes https://github.com/acidanthera/bugtracker/issues/952.
> Implement BlockIoDxe in OpenDuet

- User/Library/UserFile.c
Hi.
This is a nitpick, but before calling abort in `fwrite(...)`, the `UserWriteFile(...)` function doesn't close the file pointer, which will cause a memory leak. This PR adds `fclose(...)` before the abort.
> Close file pointer before calling abort

- Changelog.md
- Debug/efidebug.tool
In addition to existing support for 32-bit on 64-bit
> Debug: Add support for 32-bit on 32-bit under GDB

- Changelog.md
- Library/OcBootManagementLib/ImageLoader.c
Fix mentioned in changelog incorporates this and the previous commit
> OcBootManagementLib: Add missing explicit initialisation of mImageLoaderCaps in OcImageLoaderLoad

- Changelog.md
- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcBootManagementLib.h
- Include/Acidanthera/Library/OcConfigurationLib.h
- Include/Acidanthera/Library/OcPeCoffExtLib.h
- Library/OcBootManagementLib/ImageLoader.c
- Library/OcBootManagementLib/OcBootManagementLib.inf
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcMainLib/OpenCoreUefi.c
- Library/OcPeCoffExtLib/BasePeCoffLib2Internals.h
- Library/OcPeCoffExtLib/OcPeCoffExtInternal.h
- Library/OcPeCoffExtLib/OcPeCoffExtLib.c
- Library/OcPeCoffExtLib/OcPeCoffExtLib.inf
- Library/OcPeCoffExtLib/OcPeCoffFixup.c
- Utilities/AppleEfiSignTool/Makefile
Fixes https://github.com/acidanthera/bugtracker/issues/2233
For the purposes of viewing the changes, I strongly recommend https://github.com/mikebeaton/OpenCorePkg/commit/b6d5baf1e5af61b1c4b0888cd133ea02b9ca6b9f (i.e. commit 2/3), since this makes it very clear how OcPeCoffFixup.c relates to PeCoffInit.c which it came from.
- Commit 1/3 imports the two files from BasePeCoffLib2 with no changes (except renaming PeCoffInit.c -> OcPeCoffFixup.c)
- Commit 2/3 all the actual changes, making it easy to see what changed between PeCoffInit.c -> OcPeCoffFixup.c
- Commit 3/3 just the required uncrustify changes to OcPeCoffFixup.c
Since all three commits are valid builds of OpenCore (with only Uncrustify errors, only in one file, in 1/3 and 2/3), then I suggest it might be worth keeping this …
> OcPeCoffExtLib: Add support for FixupAppleEfiImages quirk

- Utilities/macrecovery/recovery_urls.txt
- Added Ventura recovery command, set to Mac-B4831CEBD52A0C4C (MacBookPro14,1)
- Updated "Latest Version" command to Mac-7BA5B2D9E42DDD94 (iMacPro1,1)
I also updated "Diagnostics" and "Default version" accordingly.
> macrecovery: Update for Sonoma

- Changelog.md
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcBootManagementLib/ImageLoader.c
The recently added "OCB: load/start unsupported ordering" error log message is unfortunately being hit on real macs when loading recovery.
This means the assumption of the original code (i.e. before the recent changes) that LoadImage and StartImage are nicely paired, at least in the cases we care about, never was being met. Storage of image caps, to transfer them between LoadImage and StartImage when needed, is now moved from a shared static variable to a protocol instance on the image handle.
Tested that it resolves the issue.
Additionally, UnloadImage was never being called when StartImage fails. Now added.
> OcBootManagementLib: Store ImageLoaderCaps in protocol.

- Include/Acidanthera/Library/OcPeCoffExtLib.h
- Library/OcPeCoffExtLib/OcPeCoffExtLib.c
- Library/OcPeCoffExtLib/OcPeCoffFixupInit.c
- Utilities/AppleEfiSignTool/AppleEfiSignTool.c
- Required to allow AppleEfiSignTool to verify rare (but actually existing) Apple signed binaries with overlapping section errors
@vit9696 - On reflection, I think this is worth adding; and with the already committed way of allowing sign tool access to the internals of the library code which it calls, it is not too messy a change after all, I think.
It works, and can validate unicorn signatures in the sign tool with the new loader + should not break anything else, I believe. :-/
> OcPeCoffExtLib: Add code path to OcPeCoffFixupInitializeContext which generates fixed image context without fixing image in memory

- Include/Apple/IndustryStandard/AppleSmBios.h
- Include/Intel/IndustryStandard/ProcessorInfo.h
- Library/OcCpuLib/AppleCpuSupport.c
Partially addresses https://github.com/acidanthera/bugtracker/issues/2366. System Information still reports an Unknown processor, presumably due to the core count exceeding the expected values for the Skylake families. But this matches the existing behavior for Alder Lake.
> OcCpuLib: Fix cpu-type detection on Raptor Lake

- Changelog.md
- Platform/OpenCanopy/Views/BootPicker.c
It seems reasonable (preferable?) to allow these keys in the case where these are being read out loud anyway by audio assist
> OpenCanopy: Enable use of picker shortcut keys when these are being read out due to audio assist

- Changelog.md
- Library/OcBootManagementLib/BuiltinPicker.c
Only just noticed that this happens, I would say it is a definite improvement to avoid this. Due to using a different approach to fetching key presses, Canopy already behaves like this.
> BuiltinPicker: Avoid responding to possibly multiple keys pressed before menu is read out, if using audio assist

- Changelog.md
- OpenDuetPkg.dsc
Should address https://github.com/acidanthera/bugtracker/issues/2371
> OpenDuet: Apply UE loader Pcds which are required to load current Linux EFI stubs

- Changelog.md
- Library/OcApfsLib/OcApfsConnect.c
apfs.efi has W^X errors which require fixup for strict loaders, however we were only passing the post-sanitised image to OC-wrapped platform loader, therefore the wrapper in ImageLoader.c cannot detect that it is an Apple signed binary which should be fixed up.
Fixes issue reported here: https://github.com/acidanthera/bugtracker/issues/2363#issuecomment-1896210279
> OcApfsLib: Always load JumpStart APFS directly

- Utilities/macrecovery/macrecovery.py
Downloading the big file first (BaseSystem) and then the chunklist may result in a token timeout for people with slow internet connections, to work around this simply moving the order of download so that the chunklist downloads first solves this issue.
> Utilities: change order of download in macrecovery

- .github/workflows/analyze.yml
- .github/workflows/build.yml
- .github/workflows/uncrustify.yml
- Bump GH actions, old ones based on Node 16 are deprecated.
- Use Apple silicon images, this will speed up builds on Mac, see https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
- Merge steps.
- ~~Switch back to ubuntu-latest, now it's `22.04`.~~
- Reuse env variables.
> Tweak GHA configs

- OpenDuetPkg.dsc
- OpenDuetPkgDefines.fdf.inc
- build_duet.tool
For reasons currently unknown, unoptimized Duet will not start in qemu (continually restarts, before any debugging output). However it seems potentially extremely useful to have a version of Duet which can be run in qemu with all debug output streaming to serial, and with ASSERTs enabled, once they can be. It seams reasonable to make NOOPT Duet permanently like this?
> OpenDuet: Debug updates

- Platform/CrScreenshotDxe/CrScreenshotDxe.c
(such as recently updated DEBUG version of OpenDuet)
> CrScreenshotDxe: Work around TPL-related ASSERT within firmware compiled to assert

- Docs/Configuration.tex
When I was reading the Sample.plist file in Xcode, I noticed that the cascading entries are perfectly ordered in alphabetical order and caps-lock first. Nice.
When I switched to the official Configuration document, however, I found that some entries are not listed like the Sample file, and this made me very confusing, because I had to scroll up/down in the document different times to find the specific entry description. So I fixed the order by Cut/Paste the wrong order sections.
This are the sections involved:
- Misc –> Properties
- Misc –> Boot Properties
- Misc –> Security Properties
- PlatformInfo –> Properties
- PlatformInfo –> Generic Properties
- PlatformInfo –> DataHub Properties
- PlatformInfo –> PlatformNVRAM Properties
- PlatformInfo –> SMBIOS Properties
- UEFI –> AppleInput …
> Docs: Fix alphabetical order on some entries in the Configuration file.

- .github/workflows/analyze.yml
- .github/workflows/build.yml
Now macos-latest is moved to Arm64.
See https://github.com/actions/runner-images?tab=readme-ov-file#available-images.
Follow up #526.
> Go back to macos-latest

- Changelog.md
- Library/OcBootManagementLib/ImageLoader.c
Note: EFI_SUCCESS does not always mean a signature was found and verified (which cannot happen for a fat slice), but simply that no further verification of SB status is required and OC image loader should be used.
Resolves: https://github.com/acidanthera/bugtracker/issues/2414
> OcBootManagementLib: Revert changes to fat slice secure boot logic from 125d8e8df36bd7ca12085d9670dca9060cf49c76

- Include/Intel/IndustryStandard/ProcessorInfo.h
- Library/OcAppleKernelLib/CpuidPatches.c
- Library/OcCpuLib/OcCpuLib.c
AMD 9000 Series CPUs have changed from Family 19h to 1Ah.
Tested and confirmed to boot.
> Add support for AMD_CPU_EXT_FAMILY_1AH

- Changelog.md
- Library/OcAppleKernelLib/CommonPatches.c
This fully resolves and closes https://github.com/acidanthera/bugtracker/issues/2410.
> OcAppleKernelLib: Fix `AppleXcpmExtraMsrs` on macOS 15

- Include/Acidanthera/Library/OcBootManagementLib.h
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcBootManagementLib/DefaultEntryChoice.c
- Platform/OpenCanopy/Views/BootPicker.c
- Platform/OpenLegacyBoot/OpenLegacyBoot.c
External is already used for:
- External picker (as opposed to builtin)
- External file system (as in, which icon to show in Canopy, or whether to mark entry “ (external)” in builtin picker)
- External Tool (user defined tool)
- External OS (user defined entry; it is also used for entries from boot entry protocol*)
- External Boot System
This PR suggests changing the last one to Unmanaged Boot This is a PR split off from https://github.com/acidanthera/OpenCorePkg/pull/549. I found it easier to work on that after these changes, which is why it was included in there in the first place.
**EDIT**: See additional explanation in comment below.
(*I only spotted this starred point while separating out this PR. I wonder if these should really have been Other OS instead of External OS all along? …
> OcBootManagementLib: Convert naming from External System Boot to Unmanaged Boot

- Changelog.md
- Include/Acidanthera/Library/OcDevicePathLib.h
- Library/OcBootManagementLib/BootEntryManagement.c
- Library/OcDevicePathLib/OcDevicePathLib.c
Apparently macOS strips down HD nodes from virtio blk devices leaving them "infix" shortened, i.e. PCI/APFS instead of PCI/HD/APFS.
> OcBootManagementLib: Add Apple DP expansion for virtio blk

- Include/Intel/IndustryStandard/ProcessorInfo.h
Defined the CPU family wrong. This fixes it.
> Fix wrong definition for AMD_CPU_EXT_FAMILY_1AH

- Library/OcBlitLib/OcBlitLib.c
- OpenCorePkg.dsc
Without this flag MSVC produces spurious warning C4324 when the macro is working as intended.
Add static assert to OcBlitLib.c which fails without this support.
Requires https://github.com/acidanthera/audk/pull/71.
> Build: Add /wd4324 to MSFT:*_CC_FLAGS for VS2019 BASE_ALIGNAS

- Library/OcCpuLib/FrequencyDetect.c
This patch addresses a bug that would cause OpenCore to freeze on a Virtualization Framework VM. Now, MSR_IA32_TSC_ADJUST is only read when the CPU supports it.
Fixes: https://github.com/acidanthera/bugtracker/issues/2463
> read MSR_IA32_TSC_ADJUST only if CPU supports

- Docs/Configuration.tex
- Docs/Sample.plist
- Docs/SampleCustom.plist
- Include/Acidanthera/Library/OcAfterBootCompatLib.h
- Include/Acidanthera/Library/OcConfigurationLib.h
- Include/Acidanthera/Protocol/OcFirmwareRuntime.h
- Library/OcAfterBootCompatLib/OcAfterBootCompatLib.c
- Library/OcAfterBootCompatLib/ServiceOverrides.c
- Library/OcConfigurationLib/OcConfigurationLib.c
- Library/OcMainLib/OpenCoreUefi.c
- Platform/OpenRuntime/UefiRuntimeServices.c
- Utilities/ocvalidate/ValidateBooter.c
This quirk is needed to boot macOS 10.7 and older when using a 32-bit kernel on a 64-bit UEFI firmware that makes uses of FPU or SSE instructions in runtime services (such as Hyper-V).
> Add ClearTaskSwitchBit booter quirk

- Docs/Sample.plist
- Docs/SampleCustom.plist
- OpenCorePkg.dsc
- build_oc.tool
Last week I spent some time on a task related to testing the network stack, namely, finding scenarios to do it correctly.
The most suitable scenario is to test network boot in a minimal UEFI environment, namely OpenDuet.
As a result, I found that for the virtio devices provided by QEMU to work correctly, their drivers need to be loaded, which are missing from our package.
(those drivers are bundled by default with OVMF, that is why we have no problem with it out of QEMU-seabios boot scenario)
To facilitate automated network boot testing in OpenDuet as part of CI, we could provide the missing drivers along with our bootloader.
> Build: Add drivers for QEMU virtio devices into build

- User/SilenceZlibWarnings
- Utilities/TestDiskImage/Makefile
- Utilities/TestKextInject/Makefile
- Utilities/TestProcessKernel/Makefile
Also refactor to remove some duplication in zlib warning code.
Silences the error here https://github.com/acidanthera/OpenCorePkg/actions/runs/14961547077/job/42024258301
> Utilities: Silence additional zlib warning triggered by update to brew mingw-w64

- Library/OcAppleKernelLib/CpuidPatches.c
This would hopefully fully fix the ASSERT issue that is present in issue (2409) in the bugtracker.
Confirmed to work on a different user with the same ASSERT issue.
> Add missing zero check for CPUFrequency on AMD CPUs

- Library/OcConsoleLib/ConsoleFontLoader.c
OcLoadConsoleFont currently loads the specified console path from `Resources\Font\\`, which can cause vault failures if vault.plist doesn't include the duplicate path separator. Remove it to match other paths.
> OcConsoleLib: Normalize console font path
