acidanthera/OpenCorePkg

Docs/AcpiSamples/SSDT-PLUG.dsl
These are the CPU names for AMD Ryzen Zen and Zen 2 CPUs.
=> Added CPU naming

Docs/AcpiSamples/SSDT-PLUG.dsl
=> SSDT-PLUG: reduced code

.shellcheckrc, .travis.yml, Debug/efidebug.tool, Docs/BuildDocs.tool, macbuild.tool
Closes acidanthera/bugtracker/#902
=> Add ShellCheck to OpenCorePkg CI

.travis.yml, Utilities/CreateVault/create_vault.sh, Utilities/LogoutHook/LogoutHook.command
=> Update ShellCheck CI

.travis.yml
=> Set ShellCheck CI Severity to "Info"

.travis.yml
Eliminate unnecessary "brew clean up" run in Travis CI Mac VM
=> Speed up HomeBrew Deployment

Application/ResetSystem/ResetSystem.c
Based on 
[audk/ShellPkg/Library/UefiShellLevel2CommandsLib/Reset.c](https://github.com/acidanthera/audk/blob/master/ShellPkg/Library/UefiShellLevel2CommandsLib/Reset.c)@[f675a1b](https://github.com/acidanthera/audk/commit/f675a1b42235b508e17220878453b4b1f04dd990)
=> OCRST: Support reboot into firmware

Docs/Configuration.tex, Include/Acidanthera/Library/OcAfterBootCompatLib.h, Include/Acidanthera/Library/OcConfigurationLib.h, Library/OcAfterBootCompatLib/BootCompatInternal.h, Library/OcAfterBootCompatLib/CustomSlide.c, Library/OcAfterBootCompatLib/OcAfterBootCompatLib.c, Library/OcConfigurationLib/OcConfigurationLib.c, Platform/OpenCore/OpenCoreUefi.c
https://github.com/acidanthera/bugtracker/issues/979
Some higher slides may be unavailable and sometimes can cause boot failure when generated random slide fall into this range.
=> Allow specification of max slide for unavailable range

Include/Acidanthera/Library/OcAppleKernelLib.h, Include/Acidanthera/Library/OcStringLib.h, Library/OcAppleKernelLib/CachelessContext.c, Library/OcAppleKernelLib/CachelessInternal.h, Library/OcAppleKernelLib/OcAppleKernelLib.inf, Library/OcStringLib/OcAsciiLib.c, Library/OcStringLib/OcUnicodeLib.c, Platform/OpenCore/OpenCoreKernel.c
references acidanthera/bugtracker#358
=> OcAppleKernelLib: Implement 64-bit cacheless kext injection

Include/Acidanthera/Library/OcDevicePathLib.h, Include/Acidanthera/Library/OcFileLib.h, Library/OcAudioLib/OcAudio.c, Library/OcBootManagementLib/AppleHibernate.c, Library/OcBootManagementLib/BootEntryManagement.c, Library/OcBootManagementLib/BootManagementInternal.h, Library/OcDevicePathLib/OcDevicePathLib.c, User/Library/OcDummy.c, User/Makefile
closes acidanthera/bugtracker#991
=> OcDevicePathLib: Fix matching disk controllers with legacy OPROM

Changelog.md, Library/OcMemoryLib/MemoryAttributes.c
closes acidanthera/bugtracker#1096
=> OcMemoryLib: Fix MAT processing for SyncRuntimePermissions

Docs/Configuration.tex
Docs: Further optimise recommended clone cmd.
Builds on https://github.com/acidanthera/OpenCorePkg/pull/78
Part of https://github.com/acidanthera/bugtracker/issues/1119
=> Docs: Further optimise recommended clone cmd

Library/OcConsoleLib/OcConsoleLibInternal.h, Library/OcConsoleLib/TextOutputBuiltin.c, Library/OcConsoleLib/TextOutputSystem.c
Closes acidanthera/bugtracker#1133
=> Return Status on Setting Renderer

Include/Acidanthera/Library/OcConsoleLib.h, Library/OcConsoleLib/ConsoleGop.c
Closes acidanthera/bugtracker#1135
=> Return Status on Providing Console GOP

User/Library/File.c
closes https://github.com/acidanthera/bugtracker/issues/1163
=> Use str as output filename

AppleModels/update_products.py, Utilities/macserial/macserial.c, Utilities/macserial/macserial.h
Fix https://github.com/acidanthera/bugtracker/issues/1195
macserial: Fix Issue #1195 (false-positive year warning for serials)
Also I really wanted to say thanks to you all guys, great project!! Wonderful 👍
=> macserial: Fix Issue #1195 (false-positive year warning for serials)

Library/OcXmlLib/OcXmlLib.c
Attempt to fix https://github.com/acidanthera/bugtracker/issues/1053
=> OcXmlLib: Try to support comments

Application/PavpProvision/PavpProvision.c, Include/Acidanthera/Library/OcAfterBootCompatLib.h, Include/Acidanthera/Library/OcConfigurationLib.h, Include/Acidanthera/Library/OcCpuLib.h, Include/Acidanthera/Library/OcFileLib.h, Include/Acidanthera/Library/OcRtcLib.h, Include/Acidanthera/Library/OcSmbiosLib.h, Include/Acidanthera/Protocol/OcFirmwareRuntime.h, Include/Apple/AppleMacEfi/AppleMacEfiSpec.h, Include/Apple/Guid/AppleFile.h, Include/Apple/IndustryStandard/AppleFeatures.h, Include/Apple/IndustryStandard/AppleRtc.h, Legacy/BootPlatform/PciRootBridgeDxe/PcatPciRootBridgeDevicePath.c, Library/OcAcpiLib/OcAcpiLib.c, Library/OcAfterBootCompatLib/BootCompatInternal.h, Library/OcAfterBootCompatLib/KernelSupport.c, Library/OcAfterBootCompatLib/ServiceOverrides.c, Library/OcAfterBootCompatLib/X64/ContextSwitch.nasm, Library/OcApfsLib/OcApfsConnect.c, Library/OcBootManagementLib/DefaultEntryChoice.c, Library/OcBootManagementLib/ImageLoader.c, Library/OcBootServicesTableLib/OcBootServicesTableLib.c, Library/OcConsoleControlEntryModeLib/OcConsoleControlEntryModeLib.c, Library/OcConsoleLib/ConsoleGop.c, Library/OcDevicePathLib/OcDevicePathLib.c, Library/OcFileLib/OpenFile.c, Library/OcInputLib/Keycode/AIK.h, Library/OcMemoryLib/MemoryAttributes.c, OpenCorePkg.dsc, Platform/OpenRuntime/UefiRuntimeServices.c
=> Extend Firmware Pluralisation Fixes

Library/OcConsoleLib/ConsoleGop.c
=> Library: Typo Fix

Docs/Configuration.tex, Docs/Sample.plist, Docs/SampleCustom.plist, Include/Acidanthera/Library/OcConfigurationLib.h, Include/Acidanthera/Library/OcSmbiosLib.h, Library/OcConfigurationLib/OcConfigurationLib.c, Library/OcSmbiosLib/SmbiosPatch.c, Platform/OpenCore/OpenCorePlatform.c, Tests/SmbiosTest/SmbiosTest.c, Utilities/TestSmbios/Smbios.c
https://github.com/acidanthera/bugtracker/issues/381
=> Custom memory properties

Docs/Configuration.tex
Fix typo in [# 135 (comment)](https://github.com/acidanthera/OpenCorePkg/pull/135#discussion_r507072308) and also fixes acidanthera/bugtracker#1225
=> Docs: Misc Fixes

Library/OcConsoleLib/TextOutputBuiltin.c
Closes acidanthera/bugtracker#1238
Three separate conditions can feed `EFI_DEVICE_ERROR` back to `OcUseBuiltinTextOutput` which leads to some difficulty discerning which one was triggered when this error is triggered. This is more so when OpenCore is used as a 3rd party library. 
This PR adds specificity to the conditions.
TODO:
=> OcConsoleLib: Improve Error Specificity in TextoutputBuiltin

Library/OcAcpiLib/OcAcpiLib.c
https://github.com/acidanthera/bugtracker/issues/1233
=> APCI table reallocation if tables are not writeable

Library/DuetBdsLib/BdsPlatform.c, OpenDuetPkg.dsc
Employ functionality from edk2.
=> [OpenDuet] Remove custom UsbLegacySupport

Docs/Configuration.tex
Following on from acidanthera/bugtracker#1461
=> Clarity on Function Prefixing

Include/Acidanthera/Library/OcAppleBootPolicyLib.h, Library/OcMainLib/OpenCoreUefi.c
Minor typos I encountered while looking in these areas of the code.
Esp. since one's a user-facing debug err msg, I thought they were worth committing.
=> OC: Fix minor typos

Docs/Configuration.tex
Addresses acidanthera/bugtracker#1494
=> Docs: Fix Itemisation

Utilities/macserial/macserial.c
Allows to build wasm macserial
=> macserial: Fix build with emcc

Docs/Configuration.tex, Library/OcSmbiosLib/SmbiosPatch.c
Try to close https://github.com/acidanthera/bugtracker/issues/1506 😊
Heads up @cdf (and as mentioned to you off-Issue)
=> Smbios: Patch from Apple tables on Apple hardware for FirmwareFeatures, PlatformFeature and SmcVersion

Changelog.md, Docs/Configuration.tex, Docs/Sample.plist, Docs/SampleCustom.plist, Include/Acidanthera/Library/OcConfigurationLib.h, Include/Acidanthera/Library/OcConsoleLib.h, Library/OcConfigurationLib/OcConfigurationLib.c, Library/OcConsoleLib/GopPassThrough.c, Library/OcConsoleLib/OcConsoleLib.inf, Library/OcConsoleLib/OcConsoleLibInternal.h, Library/OcConsoleLib/UgaPassThrough.c, Library/OcMainLib/OpenCoreUefiInOut.c
Try to close https://github.com/acidanthera/bugtracker/issues/1498
=> OpenCoreUefiInOut: Added `GopPassThrough` option to support GOP protocol over UGA

Docs/Configuration.tex
Need steer on this bit where something seems to have been skipped:
The one seems odd: `Locate Device Path of resulting Device Path`
=> Updates to Docs Section 8

Docs/Configuration.tex
=> Fix Omission in Earlier Commmit

Include/Acidanthera/Library/OcAppleKeyMapLib.h, Include/Acidanthera/Library/OcBootManagementLib.h, Include/Acidanthera/Library/OcTypingLib.h, Library/OcAppleKeyMapLib/UpDownDetection.c, Library/OcBootManagementLib/BootEntryManagement.c, Library/OcBootManagementLib/HotKeySupport.c, Library/OcBootManagementLib/OcBootManagementLib.c, Library/OcTypingLib/OcTypingLib.c
@mhaeuser in response to requested changes, could do with a re-review if possible - many thanks
=> HotKeys: Improve allocation/deallocation logic and timing

Application/ChipTune/ChipTune.c, Application/ChipTune/ChipTune.inf, Application/ControlMsrE2/ControlMsrE2.h, Application/ControlMsrE2/ControlMsrE2.inf, Application/ControlMsrE2/ControlMsrE2UI.c, Application/OpenControl/OpenControl.c, Application/OpenControl/OpenControl.inf, Application/ResetSystem/ResetSystem.c, Application/ResetSystem/ResetSystem.inf, Application/RtcRw/RtcRw.c, Application/RtcRw/RtcRw.inf, Docs/Configuration.tex
Close https://github.com/acidanthera/bugtracker/issues/1608
=> Tools: support case insensitive arguments

Docs/Sample.plist, Docs/SampleCustom.plist
Update sample files with ProvideCurrentCpuInfo added by Goldfish64
=> Update sample files with ProvideCurrentCpuInfo

Include/Acidanthera/Library/OcDeviceMiscLib.h, Library/OcDeviceMiscLib/OcDeviceMiscLib.inf, Library/OcDeviceMiscLib/PciInfoDump.c, Library/OcMainLib/OpenCoreMisc.c
closes https://github.com/acidanthera/bugtracker/issues/1445
=> OpenCore: Add PCI device info dump to SysReport

Docs/AcpiSamples/Source/SSDT-PNLF.dsl
in the previous version it only had problem with some laptops with whiskey lake cpu, but it worked on cfl and cml and icl, with new modification solved the problem.
=> SSDT-PNLF Fix code for CFL + (whiskey lake fix) 

Library/OcCompilerIntrinsicsLib/OcCompilerIntrinsicsLib.c, OpenCorePkg.dsc, OpenDuetPkg.dsc
Added auto-var-init for all compilers.
=> Auto var init

Docs/Configuration.tex
Clarifies and addresses a few typos
=> Clarify Auto Tools Usage Note

Library/OcDebugSerialLib/OcDebugSerialLib.c, Library/OcDebugSerialLib/OcDebugSerialLib.inf
=> Debug serial

Docs/Configuration.tex
Fix 2 typos in documentation file.
=> Fix typos in documentation

Docs/Sample.plist, Docs/SampleCustom.plist
https://github.com/acidanthera/bugtracker/issues/1960
=> Add comment about prev-lang:kbd (#1960)

Include/Acidanthera/Library/OcBootManagementLib.h
=> OcBootManagementLib: Fix typo

Include/Acidanthera/Library/OcAppleKernelLib.h, Library/OcAppleKernelLib/CachelessContext.c, Library/OcAppleKernelLib/MkextContext.c, Library/OcAppleKernelLib/PrelinkedContext.c, Library/OcMainLib/OpenCoreKernel.c, Utilities/TestKextInject/KextInject.c
Closes https://github.com/acidanthera/bugtracker/issues/2048
=> OcAppleKernelLib: Optionally set kext bundle version

Utilities/CreateVault/sign.command
not sure what the point of all this code this commit removes was.
guess the author didn't realize the pubkey is an output parameter, not an input one
=> remove pointless stuff from CreateVault sign.command

Platform/OpenNtfsDxe/Data.c
This is still a WIP. I will gradually work on this.
=> OpenNtfsDxe: Codestyle fixes

Docs/Configuration.tex
=> Docs: Fix typo

Library/OcAppleKernelLib/CommonPatches.c
This closes https://github.com/acidanthera/bugtracker/issues/2256
@Andrey1970AppleLife This is the integrated version of https://github.com/acidanthera/bugtracker/issues/2256#issuecomment-1487606119. Could you please test and confirm if it works? Thanks.
=> OcAppleKernelLib: Add new patch for macOS 13.3+ IOAHCIBlockStorage patch, by @vit9696

Changelog.md, Debug/README.md, Debug/Scripts/lldb_uefi.py, Debug/efidebug.tool
Also includes not-quite-working 32-bit on 64-bit LLDB support
=> Debug: Add support for 32-bit on 32-bit under LLDB

Utilities/LegacyBoot/QemuBuild.command
- Removes the fact that nothing except the code in the script documented the need to rename `boot{X64|IA32}` to `boot` before starting (and removes the need to do this)
- More or less matches the behaviour of the `BootInstall_{...}.tool` scripts, although these do not (yet?) have command line args
- Could perhaps update those scripts too, to just be one script supporting both command line args and environment variables, as done here
- Checked working on Linux and macOS(!)
=> LegacyBoot: Add ARCHS and command line args support to QemuBuild.command

build_duet.tool, build_oc.tool
Would be companion to https://github.com/acidanthera/ocbuild/pull/24 .
Note: Is expected not to build as is, as it requires the companion OcBuild change. Verification that it builds is [here](https://github.com/acidanthera/ocbuild/pull/24#issuecomment-1802077259).
=> Build: Switch to DISCARD_SUBMODULES

OpenCorePkg.dsc, OpenDuetPkg.dsc
Paired with https://github.com/acidanthera/audk/pull/65
=> UE/PE FV/NON-FV fixes - see commit comments

.gitignore, User/Include/UserEvent.h, User/Library/UserEvent.c, Utilities/TestEvent/TestEvent.c, build_oc.tool
- **Added minimal UEFI Event subsystem support into userspace**
- **Added Yummy support into UEFI in userspace**
- **Added demonstration test of working YummyEvents**
This feature added minimal support EFI Events into UEFI in userspace
Linked PR: https://github.com/acidanthera/audk/pull/77
=> Added minimal EFI Event support into userspace
